### ISSUE TITLE
Need to add an else clause when parsing column data type

### ISSUE THREAD

**Issue by jfyu** [capitalone/locopy#103] opened 2020-12-01 21:23 UTC
https://github.com/capitalone/Data-Load-and-Copy-using-Python/blob/master/locopy/utility.py#L296

There's a lot of elifs, maybe we can add an `else` clause and set it to something generic like VARCHAR. For example if we have a pandas categorical data type right now, it would just skip that column...

**Comment by fdosani** [comment] 2020-12-02 23:45
What are the teams thoughts on this? Any objections or other considerations? @dasjyao I think you might have last touched this code, so curious on your thoughts specifically?

**Comment by dasjyao** [comment] 2020-12-03 01:26
The original code was intended to handle as many dtypes as possible. With that being said, it seems still missing some cases like the `category` dtype mentioned above. I'm totally up to add an `else` and set to varchar. I can take the work if the team agrees on the idea.

**Comment by jfyu** [comment] 2020-12-03 02:35
You could also add a log warning when the `else` clause is called. 

Also, maybe you can add a keyword for custom mapping? Maybe the user have a specific set of data type mapping in mind? this might help for people who want to override the `else` if they have a data type that's not included but don't want VARCHAR. Maybe people also want a mapping from `int` to `CHAR`, for whatever reason.

**Comment by jborchma** [comment] 2020-12-03 02:46
Another thing we should do is turn the `print` statements into log calls. 

There are a few datatypes we are currently missing. Categorical is one, timedelta would be another one, for example.

**Comment by dasjyao** [comment] 2020-12-03 03:00
> You could also add a log warning when the `else` clause is called.

Yes, a log warning would be great to let people know that the column is forced into varchar type. 

> Also, maybe you can add a keyword for custom mapping? Maybe the user have a specific set of data type mapping in mind? this might help for people who want to override the `else` if they have a data type that's not included but don't want VARCHAR. Maybe people also want a mapping from `int` to `CHAR`, for whatever reason, for example, and they can now do it.

the [`insert_dataframe_to_table`](https://github.com/capitalone/locopy/blob/develop/locopy/snowflake.py#L374-L376) function already takes in a parameter that let user have the choice to pass in their own metadata.

**Comment by dasjyao** [comment] 2020-12-03 03:13
> Another thing we should do is turn the `print` statements into log calls.

I believe this has already been taken care of. See #102.
> There are a few datatypes we are currently missing. Categorical is one, timedelta would be another one, for example.

I don't know what's the best mapping for timedelta type in sql. I believe varchar can be a good generic one in this case as well. That's the reason why I would also recommend using varchar for `else` cases. Want to see if people have other opinions.

**Comment by jborchma** [comment] 2020-12-04 00:38
> > Another thing we should do is turn the `print` statements into log calls.
> 
> I believe this has already been taken care of. See #102.

Ah, didn't realize that was `master`.

**Comment by fdosani** [comment] 2020-12-24 00:20
Should be fixed now in PR #107. Closing.

**Closed by fdosani** 2020-12-24 00:20 UTC
Labels: help wanted, question
